### ISSUE TITLE
Move to keras?

### ISSUE THREAD

**Issue by rishj97** [linzh92/DeepICF#1]
Implement Deep ICF using Keras. I am curious why Keras wasn't used in the first place?

**Comment by linzh92** [comment]
Hi @wakeuprj : 

We implemented our DeepICF models based on the model of [NAIS](https://github.com/AaronHeee/Neural-Attentive-Item-Similarity-Model) which utilized Tensorflow to implement itself. You can have a try to implement DeepICF models based on the generic collaborative filtering framework of [NCF](https://github.com/hexiangnan/neural_collaborative_filtering) which is implemented by Keras.

Best regards.
