### ISSUE TITLE
When restoring pre trained variables, why not restore model.weights and mode.biases as well?

### ISSUE THREAD

**Issue by rishj97** [linzh92/DeepICF#2]
Load model.biases and model.weights [here](https://github.com/linzh92/DeepICF/blob/master/DeepICF_a.py#L231)

**Comment by rishj97** [comment]
@linzh92 Is there a reason why you decided not to do it?

**Comment by linzh92** [comment]
Hi @wakeuprj : 
       
We utilized the embeddings trained by FISM model to pre-train the models of DeepICF and DeepICF+a. The FISM model is a shallow model and there is no network weights for FISM.
You can try to leverage the embeddings, weights and biases learned by DeepICF to pre-train DeepICF+a model. There is no doubt that the performance of DeepICF+a will be better and the convergence of DeepICF+a will be faster.

Best regards.

**Comment by linzh92** [comment]
Hi @wakeuprj : 

For more details, you can read these two papers: [NAIS](https://www.comp.nus.edu.sg/~xiangnan/papers/tkde18-neural-attentive-itemCF.pdf) and [DeepICF](https://arxiv.org/pdf/1811.04392.pdf).

Best regards.
